name: joyn
description: A new Flutter application.
publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  font_awesome_flutter: ^8.8.1
  http: ^0.12.2
  pull_to_refresh: ^1.6.0
  readmore: ^1.0.0
  cached_network_image: ^2.3.1
  clippy_flutter: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
     - assets/
  fonts:
    - family: SFProDisplay
      fonts:
          - asset: fonts/SFProDisplay-Regular.ttf
    - family: Lato
      fonts:
          - asset: fonts/Lato-Regular.ttf
          - asset: fonts/Lato-Bold.ttf
            weight: 700